server:
  port: 9191

spring:
  application:
    name: GATEWAY
    cloud:
      gateway:
        enabled: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        routes:
          - id: users
            uri: lb://users
            predicates:
              - Path=/api/users/**
            filters:
            - StripPrefix=1
          - id: MULTIMEDIA-SERVICE
            uri: lb://MULTIMEDIA-SERVICE
            predicates:
              - Path=/multimedias/**

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: gateway


eureka:
  enabled: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
#  client:
#    register-with-eureka: false
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost